[tool.poetry]
name = "irca-agent"
version = "0.1.0"
description = ""
authors = ["Jean IBARZ <ibarz.jean@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
distilabel = "^1.4.1"
torch = "^2.5.1"
nltk = "^3.9.1"
python-dotenv = "^1.0.1"
transformers = "^4.46.2"
trl = "^0.12.0"
bitsandbytes = "^0.44.1"
accelerate = "^1.1.1"
peft = "^0.13.2"
protobuf = ">=3.20.0,<3.21.0"
wandb = "^0.18.6"
llama-cpp-python = "^0.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
